/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAccordion: typeof import('./src/components/atoms/TAccordion.vue')['default']
    TAccordionItem: typeof import('./src/components/atoms/TAccordionItem.vue')['default']
    TAlert: typeof import('./src/components/atoms/TAlert.vue')['default']
    TAvatar: typeof import('./src/components/atoms/TAvatar.vue')['default']
    TAvatarGroup: typeof import('./src/components/atoms/TAvatarGroup.vue')['default']
    TBadge: typeof import('./src/components/atoms/TBadge.vue')['default']
    TBreadcrumb: typeof import('./src/components/atoms/TBreadcrumb.vue')['default']
    TBreadcrumbItem: typeof import('./src/components/atoms/TBreadcrumbItem.vue')['default']
    TButton: typeof import('./src/components/atoms/TButton.vue')['default']
    TCard: typeof import('./src/components/atoms/TCard.vue')['default']
    TCarousel: typeof import('./src/components/atoms/TCarousel.vue')['default']
    TCarouselSlide: typeof import('./src/components/atoms/TCarouselSlide.vue')['default']
    TCheckboxGroup: typeof import('./src/components/atoms/TCheckboxGroup.vue')['default']
    TCollapse: typeof import('./src/components/atoms/TCollapse.vue')['default']
    TDropdown: typeof import('./src/components/atoms/TDropdown.vue')['default']
    TDropdownDivider: typeof import('./src/components/atoms/TDropdownDivider.vue')['default']
    TDropdownItem: typeof import('./src/components/atoms/TDropdownItem.vue')['default']
    TFormGroup: typeof import('./src/components/atoms/TFormGroup.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TImg: typeof import('./src/components/atoms/TImg.vue')['default']
    TInput: typeof import('./src/components/atoms/TInput.vue')['default']
    TLink: typeof import('./src/components/atoms/TLink.vue')['default']
    TModal: typeof import('./src/components/atoms/TModal.vue')['default']
    TNavbar: typeof import('./src/components/atoms/TNavbar.vue')['default']
    TOffcanvas: typeof import('./src/components/atoms/TOffcanvas.vue')['default']
    TOverlay: typeof import('./src/components/atoms/TOverlay.vue')['default']
    TPagination: typeof import('./src/components/atoms/TPagination.vue')['default']
    TPopover: typeof import('./src/components/atoms/TPopover.vue')['default']
    TProgress: typeof import('./src/components/atoms/TProgress.vue')['default']
    TRadio: typeof import('./src/components/atoms/TRadio.vue')['default']
    TRadioGroup: typeof import('./src/components/atoms/TRadioGroup.vue')['default']
    TSpinner: typeof import('./src/components/atoms/TSpinner.vue')['default']
    TTab: typeof import('./src/components/atoms/TTab.vue')['default']
    TTable: typeof import('./src/components/atoms/TTable.vue')['default']
    TTabs: typeof import('./src/components/atoms/TTabs.vue')['default']
    TTextarea: typeof import('./src/components/atoms/TTextarea.vue')['default']
    TToast: typeof import('./src/components/atoms/TToast.vue')['default']
    TTooltip: typeof import('./src/components/atoms/TTooltip.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
